adb shell "chmod 777 /data/local/tmp/MonoHook.dll"
adb shell "chmod 777 /data/local/tmp/injector"
adb shell "/data/local/tmp/injector com.unity.sampleassets /data/local/tmp/libmonohook.so"
adb shell "logcat -c"
adb shell "logcat|grep XMONO"